#!/usr/bin/env bash
# A script that installs nginx on a remote server 
# and prints "Hello World" on the index page

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
