#!/usr/bin/env bash
sudo mysqldump -u root --all-databases > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
sudo tar -czvf "$file_name" backup.sql
