#!/usr/bin/env bash
# A bash script that gives you information about the school file
my_file="school"
if [ -e $my_file ]
then
	echo "school file exists"
	if [ ! -s $my_file ]
	then
		echo "school file is empty"
	elif [ -s $my_file ]
	then
		echo "school file is not empty"
	elif  [ -f $my_file ]
	then
		echo " school file is a regular file"
	elif [ ! -f $my_file ]
	then
		echo
	fi
else
	echo "school file does not exists"
fi
